[terminal]
# 自定义shell
shell = "D:\\Powershell\\pwsh.exe"

[window]
opacity = 0.85

[font]
# 自定义字体字号
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
size = 16

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" }
]

[keyboard]
bindings = [
    { key = "Space", mods = "Control",  action = "ToggleViMode" },
    { key = "t", mods = "Control | Shift",  action = "CreateNewWindow" },
    { key = "q", mods = "Control | Shift",  action = "Quit" },
]
