[opener]
edit = [
	{ run = "nvim %0", desc = 'Edit with nvim',  block = true, for = "windows" },
	{ run = "nvim $0", desc = 'Edit with nvim',  block = true, for = "linux" },
]
open = [
	{ run = 'start "%0"', desc = "Open", block = false, for = "windows" },
	{ run = "xdg-open $0", desc = 'Open',  block = true, for = "linux" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$1")"',           desc = "Reveal", for = "linux" },
	{ run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
	{ run = 'ya pub extract --list %*',   desc = "Extract here", for = "windows" },
]
play = [
	{ run = 'xdg-open "$1"',                desc = "Play", for = "linux" },
	{ run = 'start "%1"', orphan = true, desc = "Play", for = "windows" },
]


[open]
rules = [
    # 目录
    { url = "*/", use = [ "edit", "open", "reveal" ] },
    # Text
	{ mime = "text/*", use = [ "edit", "reveal" ] },
	# Image
	{ mime = "image/*", use = [ "open", "reveal" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] }, 
    # Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },
    # fallback
    { url = "*", use = [ "open", "reveal" ] },
]
